# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :tests do
    run_tests(scheme: "Core Tests")
  end

  lane :beta do
    increment_build_number(xcodeproj: "App/App.xcodeproj")
    run_tests(scheme: "Core Tests")
    build_app(scheme: "App", destination: ".build")
    upload_to_testflight
  end
end
